version: '2'
services:
  lb:
    image: traefik:latest
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    ports:
      - "9000:80"
      - "8081:80"
      - "9001:8080"

  nginx:
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html/
    labels:
      - "traefik.frontend.rule=PathPrefix:/static/"
      - "traefik.backend=nginx"
      - "traefik.port=80"
      - "traefik.weight=5"

  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=django-ussd-airflow
      - POSTGRES_PASSWORD=django-ussd-airflow
    ports:
      - 5444:5432
    labels:
      - "traefik.enable=false"

  rabbitmq:
    image: rabbitmq:3.5.7-management
    ports:
      - 15680:15672


  app:
    build: .
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./:/usr/src/app
    links:
      - db
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//
      - CODACY_PROJECT_TOKEN=7911468d4aa94f0f941148a355a953d0
      - CODECOV_TOKEN=b9e923ec-1dea-4111-bc1c-ecaf28c0f0da
      - 'DATABASE_URL=postgres://postgres:django-ussd-airflow@db:5432/django-ussd-airflow'
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.backend=web"
      - "traefik.port=80"
      - "traefik.weight=3"
    ports:
      - 8007:80

  worker:
    build: .
    depends_on:
      - db
      - rabbitmq
    command: ./worker_server.sh
    volumes:
      - ./:/usr/src/app
    links:
      - db
      - rabbitmq
    environment:
      -  C_FORCE_ROOT=true
      -  CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//
    labels:
      - "traefik.enable=false"

  compile_documentation:
    build: .
    volumes:
      - ./:/usr/src/app
    command: make -C /usr/src/app/docs html
    labels:
      - "traefik.enable=false"

  documentation:
    image: python:3.3.6-alpine
    depends_on:
      - compile_documentation
    working_dir: /usr/src/app/docs/_build/html
    volumes:
      - ./docs/_build/html:/usr/src/app/docs/_build/html
    command: python -m http.server
    ports:
      - 7000:8000
    labels:
      - "traefik.enable=false"