version: '2'
services:
  lb:
    image: dockercloud/haproxy:1.5.1
    depends_on:
      - app
      - nginx
    links:
      - app
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9000:80'

  nginx:
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html/
    environment:
      - VIRTUAL_HOST=http://*/static/*
      - VIRTUAL_HOST_WEIGHT=3

  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=django-ussd-airflow
      - POSTGRES_PASSWORD=django-ussd-airflow
      - POSTGRES_USER=django-ussd-airflow
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.5.7-management
    ports:
      - 15680:15672


  app:
    build: .
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./:/usr/src/app
    links:
      - db
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//
      - VIRTUAL_HOST=http://*/*

  worker:
    build: .
    depends_on:
      - db
      - rabbitmq
    command: ./worker_server.sh
    volumes:
      - ./:/usr/src/app
    links:
      - db
      - rabbitmq
    environment:
      -  C_FORCE_ROOT=true
      -  CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//